---

- name: Create User Group
  group:
    name='named'
    gid=25
    state='present'
  when: named_travis_ci is not defined
  tags: install

- name: Add User
  user:
    name='named'
    uid=25
    group='named'
    home={{ named_conf_directory }}
    shell={{ named_user_shell }}
    system='yes'
  when: named_travis_ci is not defined
  tags: install

- name: Create log Directory
  file:
    path={{ named_conf_logging_file_directory }}
    owner={{ named_user }}
    group={{ named_group }}
    mode={{ named_conf_logging_directory_perms | default("750") }}
    state='directory'
    setype=named_log_t
  tags: install

- name: Create log file
  command: touch "{{ named_conf_logging_file_directory }}/{{ named_conf_logging_file }}"
  args:
    creates: "{{ named_conf_logging_file_directory }}/{{ named_conf_logging_file }}"

- name: Reset selinux permissions
  file:
    path={{ named_conf_logging_file_directory }}/{{ named_conf_logging_file }}
    owner={{ named_user }}
    group={{ named_group }}
    mode="660"
    setype=named_log_t
  when: ansible_selinux.mode == 'enforcing'
  tags: install


- name: Create includes Directory
  file:
    path={{ named_conf_includes_directory }}
    owner={{ named_user }}
    group={{ named_group }}
    state='directory'
    mode="0770"
  tags: install

- name: Create zone masters Directory
  file:
    path={{ named_conf_directory }}/masters
    owner={{ named_user }}
    group={{ named_group }}
    mode={{ named_masters_directory_perms }}
    state='directory'
  tags: install
